import Head from "next/head";
import Login from "../components/Login";
import Sidebar from "./../components/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </>
  );
}
